spring.application.name=app

spring.datasource.url= jdbc:postgresql://localhost:5432/myDB
spring.datasource.username= student
spring.datasource.password= chocolatefrog
spring.jpa.hibernate.ddl-auto= validate

server.port = 8080

telegram.bot.token=8448273341:AAFcYWDudslDF2u5RCoxdJsQzAem_RsGsp4

spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml